image: docker:19

stages:
  - test
  - deploystaging

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Test:
  stage: test
  only:
    - tags
  script:
    - ./gradlew test

Deploy staging:
  stage: deploystaging
  only:
    - tags
  script:
    - echo "Started deploying to $PBS_OX_STAGING_FREENAS_HOST"
    - ./gradlew deploy -Dserver=staging
  after_script:
    - curl https://ox-staging.pbs.gov.au/login.html?berlioz-reload=true
