image: docker:19

stages:
  - deployproduction

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Deploy production:
  stage: deployproduction
  only:
    - tags
  script:
    - echo "Started deploying to $MPS4_PRODUCTION_FREENAS_HOST"
    - ./gradlew deploy -Dserver=production